const flowbite = require("flowbite-react/tailwind");
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}", flowbite.content()],
  theme: {
    extend: {
      colors: {
        indigo: { 500: "#A9D6E5", 400: "#48cae4 " },
        text: "#343a40",
        text2: "#010203",
        headerFooterSidebar: "#19747E",
        textImp: "#ffc107",
        textError: "#ff6347",
        bg2: "#D1E8E2",
        active: "#A9D6E5",
        button: "#48cae4",
        card: "#D1E8E2",
        grey: "#808080",
        bg: "#eceff7",
        pinkLight: "#eec8e9",
        babyPink: "#efd5e6",
        greyLight: "#f5f5f5",
        borderGrey: "#ebebeb",
        textGrey: "#b2b2b2",
        chips: "#e7e7e9",
        instructorDash: "#fcb03f",
        bodyBg: "#efefef",
        cblue: "#007EFE",
        cwhite: "#FFFFFF",
        cblack: "#5E5E5E",
        clightgray: "#F6F6F6",
        csemilightgray: "#D5D5D5",
        cgray: "#929292",
        cdardgray: "#929292",
        cseagreen: "#f2faff",
        cgreen: "#bafc4f",
        clightgreen: "#e1ffdc",
        csubMenu: "#e2ecfe",
        cblueScond: "#00a2ff",
        corange: "#FF8000",
        cchartburnt: "#adadad",
        cchartover: "#ed6772",
        cchartunder: "#fce994",
        cchartInzone: "#85d996",
      },

      fontFamily: {
        custom: ["DM Sans", "sans"],
      },
    },
  },
  plugins: [flowbite.plugin()],
};
